#!/bin/bash

echo "ICC INTRISICS"
echo "============="
./icc_100k
echo "============="
./icc_1000k
echo "============="
./icc_5000k
echo "============="
./icc_10000k
echo "============="
./icc_20000k
echo "============="

